# Generated by Django 5.1.6 on 2025-03-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_tracker", "0002_transaction_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")], max_length=20
            ),
        ),
    ]
